### ISSUE TITLE
imdblib request

### ISSUE THREAD

**Issue by giuseppecrc** [IMDb-API/IMDbApiLib#1]
Hi!
it's possible to implement web proxy?
thanks!

**Comment by IMDb-API** [comment]
Hi, The short answer is NO!
You can fork this library and change **Utils.cs**


```C#
var proxy = new WebProxy();
proxy.Address = new Uri("mywebproxyserver.com");
proxy.Credentials = new NetworkCredential("usernameHere", "password");
proxy.UseDefaultCredentials = false;
proxy.BypassProxyOnLocal = false;

var client = new WebClient();
client.Proxy = proxy;
// ...
```

Reference:
https://stackoverflow.com/questions/817548/c-sharp-webclient-and-proxy-server

In the next version, we will definitely add a proxy.

**Comment by IMDb-API** [comment]
The possibility of using a proxy was added.
