### ISSUE TITLE
Advanced Search generates invalid URL for TitleType

### ISSUE THREAD

**Issue by richsch** [IMDb-API/IMDbApiLib#10]
`AdvancedSearchInput.ToString()` has `title_type` listed twice.

ie.
```
var input = new AdvancedSearchInput
{
     TitleType = AdvancedSearchTitleType.Video
};
var text = input.ToString();
```
will produce `?title_type=video&title_type=video`

**Comment by richsch** [comment]
Following on this - two genres have incorrect Description values, meaning that the search by genre fails:

- `Film_Noir` has description `noir` (should be `film_noir`)
- `Sci_Fi` has description `fi` (should be `sci_fi`)

**Comment by HaddadCSharp** [comment]
Thanks for the bug report. problem solved.
