### ISSUE TITLE
Parse title Fr lang

### ISSUE THREAD

**Issue by webkubikc** [IMDb-API/IMDbApiLib#2]
Hello. How do I get a title in French?

**Comment by IMDb-API** [comment]
Hi
You can use the Wikipedia API
https://imdb-api.com/fr/API/Wikipedia/{apiKey}/{id}

{
  ...
  "titleInLanguage": "Title in FR Language"
  ...
}

**Comment by webkubikc** [comment]
Thank you so much))

**Comment by webkubikc** [comment]
Can i also get genres in French ?

**Comment by IMDb-API** [comment]
You just need to translate the following genres into your own language
https://www.imdb.com/feature/genre

Lis of genres:
- Action
- Adventure
- Animation
- Biography
- Comedy
- Crime
- Documentary
- Drama
- Family
- Fantasy
- Film Noir
- Game Show
- Historical
- Historical fiction
- History
- Horror
- Magical realism
- Music
- Musical
- Mystery
- News
- Paranoid fiction
- Philosophical
- Political
- Reality TV
- Reality-TV
- Romance
- Saga
- Satire
- Sci-Fi
- Science fiction
- Short Film
- Social
- Speculative
- Sport
- Sports
- Superhero
- Talk Show
- Thriller
- Urban
- War
- Western

.../fr/APII/Title/{apiKey}/{id}
> {
>	"id": "tt1375666",
>	"title": "Inception",
>	"originalTitle": "",
>	"fullTitle": "Inception (2010)",
>	"type": "Movie",
>	"year": "2010",
>	...
>	"genres": "Action, Adventure, Sci-Fi, Thriller",
>	"genreList": [
>		 {
>			"key": "Action",
>			"value": "Action"
>		 },
>		 {
>			"key": "Adventure",
>			"value": "Adventure"
>		 },
>		 {
>			"key": "Sci-Fi",
>			"value": "Sci-Fi"
>		 },
>		 {
>			"key": "Thriller",
>			"value": "Thriller"
>		 }
>	],
>	...
> }

There is no translation of genres into French in our system. We did not find anyone for translating genres into French and we did not want to use machine translation.
If we receive a proper translation of the genres in any language, we will put it on the site.

**Comment by webkubikc** [comment]
Hello. Thank you very much for the answer, the only implementation of genre
translation into any language I saw only in themoviedb

**Comment by IMDb-API** [comment]
Hello again, the list of TheMovieDb genres like IMDb is not complete. Our movie genres are read from IMDb.

**TheMovieDb genres in French language:**
en
fr
___
Action
Action
___
Adventure
Aventure
___
Animation
Animation
___
Biography
?
___
Comedy
Comédie
___
Crime
Crime
___
Documentary
Documentaire
___
Drama
Drame
___
Family
Familial
___
Fantasy
Fantastique
___
Film Noir
?
___
Game Show
?
___
Historical
?
___
Historical fiction
?
___
History
Histoire
___
Horror
Horreur
___
Magical realism
?
___
Music
Musique
___
Musical
?
___
Mystery
Mystère
___
News
?
___
Paranoid fiction
?
___
Philosophical
?
___
Political
?
___
Reality TV
?
___
Reality-TV
?
___
Romance
Romance
___
Saga
?
___
Satire
?
___
Sci-Fi
?
___
Science fiction
Science-Fiction
___
Short Film
?
___
Social
?
___
Speculative
?
___
Sport
?
___
Sports
?
___
Superhero
?
___
Talk Show
?
___
Thriller
Thriller
___
Urban
?
___
War
Guerre
___
Western
Western
___
