### ISSUE TITLE
How to fetch all information about movie?

### ISSUE THREAD

**Issue by antontuz** [IMDb-API/IMDbApiLib#3]
I have a movie "12 angry men". How to get all information about this movie?
I'm trying to do this: 
`
var apiLib = new ApiLib("API-Key");
var data = await apiLib.SearchMovieAsync("12 angry men");
cw(data); // i doesn't return any information
`
If I had id (for example, tt0110413) I would try to do this:
`
var data = await apiLib.TitleAsync("tt0110413");
var title = data.title; //etc
cw(title); 
`

**Comment by IMDb-API** [comment]
Hi, Make sure that you are using the latest version of IMDbApiLib (v1.5).

Code:

    // PM> Install-Package IMDbApiLib -Version 1.5.0
    var apiLib = new ApiLib("API-Key");

    // https://github.com/IMDb-API/IMDbApiLib/blob/master/IMDbApiLib/Models/SearchData.cs
    var data = await apiLib.SearchMovieAsync("12 angry men");
    if (string.IsNullOrEmpty(data.ErrorMessage) && data.Results.Count > 0)
    {
        string imdbId = data.Results.First().Id;   // tt0050083

        // https://github.com/IMDb-API/IMDbApiLib/blob/master/IMDbApiLib/Models/TitleData.cs
        var titleData = await apiLib.TitleAsync(imdbId);
    }

**Comment by antontuz** [comment]
thanks a lot, your lib is so cool. I'm trying to use it on my college project
