### ISSUE TITLE
Search by IMDb Score

### ISSUE THREAD

**Issue by theboulderking** [IMDb-API/IMDbApiLib#4]
Wonder if it's possible to search all movies by a IMDb score range? Or really any search by genre, year, actor, or director. Is that something that could be accomplished the way the data is structured?

**Comment by IMDb-API** [comment]
No Unfortunately, these services are not implemented, we may add an advanced search to the site features in the future.

**Comment by theboulderking** [comment]
is this something I could fork this repo for and implement? or are there data structure changes needed?

**Comment by heywoodg** [comment]
It would be really useful to have API access to the advanced search. I know technically we can scrape it, but I understand it isn't allowed, and it is always good to be able to do things the right way!

**Comment by IMDb-API** [comment]
These changes should only be made from the server side.
Advanced search capability will be added soon.

**Comment by heywoodg** [comment]
That is great news, thanks!

**Comment by IMDb-API** [comment]
Advanced search was added to the site and the Nugget package.
