### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by matthewblott** [IMDb-API/IMDbApiLib#7]
On the home page it says this is an Avalonia project but I can't see any references to Avalonia. This seems like a standard WinForms application. Am I missing something here? Thanks :-)

**Comment by IMDb-API** [comment]
The source of the Avalonia project is not included because it is old. Only Winforms project is developed.

**Comment by matthewblott** [comment]
It might be an idea to remove macOS and Linux interfaces from your home screen. It's confusing.

**Comment by IMDb-API** [comment]
Version 1.6.3.1 is available for all operating systems.
https://github.com/IMDb-API/IMDbApiClient/releases/tag/1.6.3.1
