### ISSUE TITLE
Retrieve title of movie in specific language

### ISSUE THREAD

**Issue by JackDjTom** [IMDb-API/IMDbApiLib#8]
Hi there,

I was wondering whether there is a possiblity to retrieve the title of a movie in a given language.

When I have the following code with the language '**de**' for german:
```cs
TitleData? title = await api.TitleAsync("tt0241527", IMDbApiLib.Models.Language.de);
```
I get a `TitleData` object with the Title 'Harry Potter and the Sorcerer's Stone' and an empty string for the OriginalTitle.
Only the Plot is in german. But I need the title in german ('Harry Potter und der Stein der Weisen')

In some forums I found that you have to set the request header "Accept-Language" to the specific language, but I couldn't get that to work either.

Is there any way to get the title in german?

**Comment by HaddadCSharp** [comment]
Hello, use the [Wikipedia](https://imdb-api.com/api#Wikipedia-header) service to get movie titles in other languages (titleInLanguage field).

```csharp
var data = await apiLib.WikipediaAsync("tt0241527", IMDbApiLib.Models.Language.de);
Console.WriteLine(data.TitleInLanguage); // Harry Potter und der Stein der Weisen
```

**Comment by JackDjTom** [comment]
Thanks a lot!
